from collections import defaultdict, deque
import json
from pathlib import Path

events_file = Path("lineage_events.json")

if not events_file.exists():
    print("[ERROR] File lineage_events.json not found. Run 'python emit_lineage_events.py'.")
    exit(1)

with open(events_file, "r", encoding="utf-8") as f:
    events = json.load(f)

print("=" * 75)
print("⚠️  DYNAMIC DOWNSTREAM IMPACT ANALYSIS (OPENLINEAGE BLAST RADIUS)")
print("=" * 75)

target_column = "amount"
origin_dataset = "transactions.parquet"

print(f"\n[ENTERPRISE SCENARIO]:")
print(f"Upstream team intends to rename or drop column '{target_column}' in '{origin_dataset}'.")
print("Analyzing OpenLineage metadata (COMPLETE events) and calculating dynamic Blast Radius...\n")

# 1. Build Directed Bipartite Graph (Dataset -> Job -> Dataset)
dataset_to_jobs = defaultdict(list)
job_to_datasets = defaultdict(list)
dataset_schemas = {}
dataset_namespaces = {}
job_namespaces = {}

for event in events:
    if event.get("eventType") != "COMPLETE":
        continue

    job_info = event.get("job", {})
    job_name = job_info.get("name")
    job_namespaces[job_name] = job_info.get("namespace", "unknown")

    # Map Input Datasets -> Job
    for inp in event.get("inputs", []):
        ds_name = inp.get("name")
        dataset_namespaces[ds_name] = inp.get("namespace", "")
        if job_name not in dataset_to_jobs[ds_name]:
            dataset_to_jobs[ds_name].append(job_name)

        if "schema" in inp.get("facets", {}):
            dataset_schemas[ds_name] = [
                field["name"] for field in inp["facets"]["schema"].get("fields", [])
            ]

    # Map Job -> Output Datasets
    for out in event.get("outputs", []):
        ds_name = out.get("name")
        dataset_namespaces[ds_name] = out.get("namespace", "")
        if ds_name not in job_to_datasets[job_name]:
            job_to_datasets[job_name].append(ds_name)

        if "schema" in out.get("facets", {}):
            dataset_schemas[ds_name] = [
                field["name"] for field in out["facets"]["schema"].get("fields", [])
            ]

# 2. Validate column presence at root node
if origin_dataset in dataset_schemas:
    fields = dataset_schemas[origin_dataset]
    if target_column in fields:
        print(f"[*] Confirmed root origin: '{origin_dataset}' contains '{target_column}' in SchemaFacet.")
    else:
        print(f"⚠️ Warning: '{target_column}' not found in fields of '{origin_dataset}'.")

# 3. Breadth-First Search (BFS) to traverse downstream dependencies in Graph
queue = deque([(origin_dataset, 0)])
visited_datasets = {origin_dataset}
visited_jobs = set()

impacted_by_level = defaultdict(list)

while queue:
    current_ds, depth = queue.popleft()

    # Identify jobs consuming this dataset
    consumer_jobs = dataset_to_jobs.get(current_ds, [])
    for job in consumer_jobs:
        if job not in visited_jobs:
            visited_jobs.add(job)
            impacted_by_level[depth + 1].append({
                "type": "JOB",
                "name": job,
                "namespace": job_namespaces.get(job, ""),
                "consumed_from": current_ds
            })

            # Identify outputs generated by this job
            for out_ds in job_to_datasets.get(job, []):
                # Verify if column propagates to output
                out_fields = dataset_schemas.get(out_ds, [])
                has_column = target_column in out_fields if out_fields else True

                if out_ds not in visited_datasets and has_column:
                    visited_datasets.add(out_ds)
                    impacted_by_level[depth + 2].append({
                        "type": "DATASET",
                        "name": out_ds,
                        "namespace": dataset_namespaces.get(out_ds, ""),
                        "produced_by": job,
                        "has_column": target_column in out_fields
                    })
                    queue.append((out_ds, depth + 2))

# 4. Present Blast Radius
print("\n🚨 IDENTIFIED BLAST RADIUS (DOWNSTREAM DEPENDENCY GRAPH):")

total_impacted = 0
for level in sorted(impacted_by_level.keys()):
    items = impacted_by_level[level]
    print(f"\n[Level {level}] - {len(items)} affected element(s):")
    for item in items:
        total_impacted += 1
        if item["type"] == "JOB":
            print(f"   ⚙️  [PIPELINE/JOB] {item['name']}")
            print(f"       Consumes: [{item['consumed_from']}] | Namespace: {item['namespace']}")
        else:
            schema_status = "✅ Column confirmed in SchemaFacet" if item["has_column"] else "⚠️ Schema without explicit validation"
            print(f"   📦 [IMPACTED DATASET] {item['name']}")
            print(f"       Origin: Job [{item['produced_by']}] | URI: {item['namespace']}/{item['name']}")
            print(f"       Validation: {schema_status}")

# 5. Executive Summary & Governance Action
print("\n" + "=" * 75)
print(f"📊 BLAST RADIUS SUMMARY:")
print(f"   ├─ Impacted Jobs/Pipelines: {len(visited_jobs)}")
print(f"   ├─ Corrupted Analytical Datasets: {len(visited_datasets) - 1}")
print(f"   └─ Total cascaded broken nodes: {total_impacted}")
print("\n💡 RECOMMENDED GOVERNANCE ACTION:")
print("   ❌ BLOCK upstream team Pull Request!")
print(f"   Breaking contract on column '{target_column}' would break downstream products:")
print("   Executive BI, Fraud Feature Store, and BACEN Regulatory Report.")
print("=" * 75)

